name: funny_zone_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  youtube_player_flutter: ^8.1.2
  change_app_package_name: ^1.1.0
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.3
  youtube_player_iframe: ^4.0.1
  url_launcher: ^6.1.7
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  cloud_firestore: ^4.3.1
  get_it: ^7.2.0
  youtube_video_info: ^1.0.1
  youtube_metadata: ^1.0.1
  extractor: ^0.0.3
  intl: ^0.18.0
  share_plus: ^6.3.0
  google_mobile_ads: ^2.3.0



flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/banners/
      - assets/icons/
      - assets/logo/

  